meta_product_name: "Benjamin Toosey's Portfolio"
meta_title: "Benjamin Toosey | Portfolio"
meta_description: "Welcome to my personal portfolio website! Have a look around and let me know what you think!"
meta_image: "hellothere.png"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
